
auth:
  url:
    kauth: https://kauth.kakao.com
  conn:
    connect-timeout: 3000
    read-timeout: 2000
    user-agent: lotto-portfolio

springdoc:
  default-consumes-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html