spring:
  batch:
    job:
      enabled: true
      name: ${job.name}
  config:
    activate:
      on-profile: default
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 3000
            read-timeout: 3000
