spring:
  batch:
    job:
      enabled: true
      name: ${job.name}
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 10000
            read-timeout: 10000
