spring:
  config:
    activate:
      on-profile: default
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  datasource:
    hikari:
      connection-timeout: 5000
      minimum-idle: 10
      maximum-pool-size: 100

hibernate:
  show_sql: false
  format_sql: false
  physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Vault AppRole
vault:
  uri: http://localhost:8200
  token: admin
  app-role:
    role-id:
    secret-id:
  secret:
    appconfig: oauth2-app/local