name: number-batch

on:
  workflow_dispatch:
    inputs:
      startDrwtNo:
        description: 시작회차
        default: ""
        type: string
      endDrwtNo:
        description: 종료회차
        default: ""
        type: string
  schedule:
    - cron: '0 21 * * SUN'    # 매주 일요일 21시

jobs:
  number-batch:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Gradle
        run: ./gradlew clean --stacktrace --build-file=./batch/build.gradle.kts --exclude-task test build

      - name: Upload JAR To Instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          source: "./batch/build/libs/batch-0.0.1-SNAPSHOT.jar"
          target: "/home/opc/num-deploy"

      - name: Execute Job with Remote SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            echo jobName=lottoNumberJob startDrwtNo=${{ inputs.startDrwtNo }} endDrwtNo=${{ inputs.endDrwtNo }}
            ls ~/num-deploy/batch/build/libs -all
            java -Dspring.profiles.active=prod -jar ~/num-deploy/batch/build/libs/batch-0.0.1-SNAPSHOT.jar --job.name=lottoNumberJob startDrwtNo=${{ inputs.startDrwtNo }} endDrwtNo=${{ inputs.endDrwtNo }}
            rm -rf ~/num-deploy